name: Pint
version: '${project.version}'
main: dk.martinersej.pint.Pint
database: true
depend:
  - Citizens
  - HolographicDisplays
  - Vault
  - WorldEdit
  - FastAsyncWorldEdit
  - WorldGuard
commands:
  map:
    aliases: [ ]
  game:
    aliases: [ ]
  vote:
    aliases: [ ]
  test:
    aliases: [ ]