name: Pint
version: '${project.version}'
main: dk.martinersej.pint.Pint
database: true
author: "Martin"

depend:
  - Vault
  - WorldEdit
  - FastAsyncWorldEdit
  - WorldGuard
softdepend:
  - Citizens

commands:
  map:
    aliases: [ ]
  game:
    aliases: [ ]
  vote:
    aliases: [ ]
  spawn:
    aliases: [ ]
  warp:
    aliases: [ warps ]
  showregions:
    aliases: [ ]
  test:
    aliases: [ ]
  join:
    aliases: [ ]

libraries:
  - 'net.kyori:adventure-platform-bukkit:4.0.1'